CREATE CONSTRAINT movie_id IF NOT EXISTS ON (m:Movie) ASSERT m.movieId IS UNIQUE;
CREATE CONSTRAINT genre_name IF NOT EXISTS ON (g:Genre) ASSERT g.name IS UNIQUE;
CREATE CONSTRAINT actor_name IF NOT EXISTS ON (a:Actor) ASSERT a.name IS UNIQUE;
CREATE CONSTRAINT director_name IF NOT EXISTS ON (d:Director) ASSERT d.name IS UNIQUE;
